
server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8088/user
      
hystrix:
  shareSecurityContext: true #compartilha header de autenticação da thread normail da aplicação com a thread do hystrix